<?php
/**
 * @file tagadelic.module
 * Library to build tagclouds.
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://berk.es
 */

/**
 * Implements hook_menu().
 * @see hook_menu()
 */
function tagadelic_taxonomy_menu() {
  $items['tagadelic_taxonomy'] = array(
    'title' => 'Tag Cloud',
    'page callback' => 'tagadelic_taxonomy_cloud',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  return $items;
}

/**
 * Constructs a simple page.
 */
function tagadelic_taxonomy_cloud() {
  $tags = tagadelic_taxonomy_get_tags();
  $out = theme("tagadelic_taxonomy_cloud", array("tags" => $tags));
  return $out;
}

function tagadelic_taxonomy_theme($existing, $type, $theme, $path) {
  return array(
    "tagadelic_taxonomy_cloud" => array(
      "variables" => array(
        "tags" => array(),
        "name" => "",
      ),
      "path" => "{$path}/templates",
      "template" => "tagadelic_taxonomy_cloud"
    ), // tagadelic_taxonomy_cloud

  );
}

function tagadelic_taxonomy_get_tags() {
  $tags = array();

  /**
  see http://drupal.stackexchange.com/q/54483/787
  $query = db_select('taxonomy_term_data', 't');

  $query->addField('t', 'tid');
  $query->addField('t', 'name');
  $query->addField('t', 'description');
  $query->addField('COUNT(i.nid)', 'count');

  $query->leftjoin('taxonomy_index', 'i', 'i.nid = t.nid');
  $query->range(0, 60)
    ->groupBy('i.nid');

  print($query);

  result = $query->execute();*/

  $result = db_query("SELECT t.tid, t.name, t.description, COUNT(i.nid) AS count
  FROM taxonomy_index AS i 
  LEFT JOIN taxonomy_term_data AS t ON i.tid = t.tid
  GROUP BY i.tid 
  LIMIT 60");

  /*foreach ($result as $term) {*/
  while($term = $result->fetchObject()) {
    $tag = new TagadelicTag($term->tid, $term->name, $term->count);
    $tag->set_link("taxonomy/term/{$term->tid}");
    $tag->set_weight(1);

    $tags[] = $tag;
  }

  return $tags;
}

