<?php
/**
 * @file tagadelic.module
 * Library to build tagclouds.
 * @author Bèr Kessels <ber@webschuur.com>
 * @link http://berk.es
 */

/**
 * Implements hook_menu().
 * @see hook_menu()
 */
function tagadelic_taxonomy_menu() {
  $items['tagadelic_taxonomy'] = array(
    'title' => 'Tag Cloud',
    'page callback' => 'tagadelic_taxonomy_cloud',
    'access callback' => TRUE,
    'expanded' => TRUE,
  );
  return $items;
}

/**
 * Constructs a simple page.
 */
function tagadelic_taxonomy_cloud() {
  $tags = tagadelic_taxonomy_get_tags();
  $out = theme("tagadelic_taxonomy_cloud", array("tags" => $tags));
  return $out;
}

function tagadelic_taxonomy_theme($existing, $type, $theme, $path) {
  return array(
    "tagadelic_taxonomy_cloud" => array(
      "variables" => array(
        "tags" => array(),
        "name" => "",
      ),
      "path" => "{$path}/templates",
      "template" => "tagadelic_taxonomy_cloud"
    ), // tagadelic_taxonomy_cloud

  );
}

function tagadelic_taxonomy_get_tags() {
  $terms = array();
  $query = db_select('taxonomy_term_data', 't');
  $result = $query
    ->fields('t')
    ->execute();

  foreach ($result as $term) {
    $tag = new TagadelicTag($term->tid, $term->name, 1);
    $tag->set_link("taxonomy/term/{$term->tid}");

    $terms[] = $tag;
  }

  return $terms;
}

