<?php

require_once 'TagadelicTag.php';
require_once 'TagadelicDrupalWrapper.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 15:22:10.
 */
class TagadelicTagTest extends PHPUnit_Framework_TestCase {
  /**
   * @var TagadelicTag
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->drupal = $this->getMock("TagadelicDrupalWrapper", array("check_plain", "l"));
    $this->drupal->expects($this->any())
                 ->method('check_plain')
                 ->will($this->returnArgument(0));
    $this->object = new TagadelicTag(42, "blackbeard", 2);
    $this->object->set_drupal($this->drupal);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }
}
