<?php

require_once 'TagadelicTag.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 15:22:10.
 */
class TagadelicTagTest extends PHPUnit_Framework_TestCase {
  /**
   * @var TagadelicTag
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    // function __construct($id, $name, $count, $description = "", $link = NULL) {
    $this->object = new TagadelicTag(42, "blackbeard", 2);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * @covers TagadelicTag::__ToString
   * @todo   Implement test__ToString().
   */
  public function test__ToString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::get_id
   * @todo   Implement testGet_id().
   */
  public function testGet_id()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::get_name
   * @todo   Implement testGet_name().
   */
  public function testGet_name()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::get_description
   * @todo   Implement testGet_description().
   */
  public function testGet_description()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::get_weight
   * @todo   Implement testGet_weight().
   */
  public function testGet_weight()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::set_id
   * @todo   Implement testSet_id().
   */
  public function testSet_id()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::set_name
   * @todo   Implement testSet_name().
   */
  public function testSet_name()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::set_description
   * @todo   Implement testSet_description().
   */
  public function testSet_description()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::set_link
   * @todo   Implement testSet_link().
   */
  public function testSet_link()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::set_count
   * @todo   Implement testSet_count().
   */
  public function testSet_count()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::force_dirty
   * @todo   Implement testForce_dirty().
   */
  public function testForce_dirty()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::force_clean
   * @todo   Implement testForce_clean().
   */
  public function testForce_clean()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicTag::distributed
   * @todo   Implement testDistributed().
   */
  public function testDistributed()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }
}
