<?php

require_once 'TagadelicCloud.php';
require_once 'TagadelicTag.php';
require_once 'TagadelicDrupalWrapper.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 15:23:33.
 */
class TagadelicCloudTest extends PHPUnit_Framework_TestCase {
  /**
   * @var TagadelicCloud
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new TagadelicCloud(1337);
    $this->blackbeard = $this->getMock("TagadelicTag", array(), array(13, "blackbeard", 100));
    $this->jane = $this->getMock("TagadelicTag", array(), array(14, "jane", 200));
    $this->mock_tags = array($this->blackbeard, $this->jane);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * constructor should set the ID to the variable passed.
   */
  public function test__construct() {
    // First param should be assigned to the id.
    $this->assertAttributeSame(1337, "id", $this->object);

    // Optional second argument pre-sets the tags.
    $this->object = new TagadelicCloud(1337, $this->mock_tags);
    $this->assertAttributeSame($this->mock_tags, "tags", $this->object);
  }

  /**
   * @expectedException InvalidArgumentException
   */
  public function test__construct_false_id() {
    $cloud = new TagadelicCloud("woot");
  }

  /**
   * @covers TagadelicCloud::get_id
   */
  public function testGet_id() {
    $this->assertEquals(1337, $this->object->get_id());
  }

  /**
   * @covers TagadelicCloud::get_tags
   * Tests if get_Tags returns an array only.
   */
  public function testGet_tags() {
    $this->object = new TagadelicCloud(1337, $this->mock_tags);
    $this->assertSame($this->mock_tags, $this->object->get_tags());
  }

  /**
   * @covers TagadelicCloud::add_tag
   */
  public function testAdd_tag() {
    $this->object->add_tag($this->blackbeard);
    $this->assertAttributeContains($this->blackbeard, "tags", $this->object);
  }

  /**
   * TagadelicCloud::add_tag() is chainable
   */
  public function testAdd_tagIsChainable() {
    $this->assertEquals($this->object->add_tag($this->blackbeard), $this->object);
  }

  /**
   * @covers TagadelicCloud::create_and_add_tag
   */
  public function testCreate_and_add_tag() {
    $tag = new TagadelicTag(13, "blackbeard", 37); //Cannot use mock, 'cause we create a TagadalicTag, not a mock_tagalicTag.
    $tag->set_weight(1.0);
    $this->object->create_and_add_tag(13, "blackbeard", 37);

    $test_tag = array_pop($this->object->get_tags());
    $this->assertEquals($tag, $test_tag);
  }

  /**
   * TagadelicCloud::create_and_add_tag() is chainable
   */
  public function testCreate_and_add_tagIsChainable() {
    $this->assertEquals($this->object->create_and_add_tag(13, "blackbeard", 37), $this->object);
  }

  /**
   * @covers TagadelicCloud::from_cache
   */
  public function testFrom_cache() {
    $drupal = $this->getMock("TagadelicDrupalWrapper");
    $drupal->expects($this->any())
      ->method("cache_get")
      ->with("tagadelic_cloud_1337");
    TagadelicCloud::from_cache(1337, $drupal);
  }

  /**
   * Get Tags should calculate the weights
   */
  public function testGetCalculatedTags() {
    //Implement weighting first.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
    $this->object = new TagadelicCloud(1337, $this->mock_tags);
    foreach($this->object->get_tags() as $tag) {
      $weights[] = $tag->get_weight();
    }
    $this->assertEquals($weights, array(1,2));
  }
}
