<?php

require_once 'TagadelicCloud.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-05-16 at 15:23:33.
 */
class TagadelicCloudTest extends PHPUnit_Framework_TestCase {
  /**
   * @var TagadelicCloud
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new TagadelicCloud(1337);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
  }

  /**
   * constructor should set the ID to the variable passed.
   */
  public function test__construct() {
    $this->assertAttributeSame(1337, "id", $this->object);
  }
  /**
   * @expectedException InvalidArgumentException
   */
  public function test__construct_false_id() {
    $cloud = new TagadelicCloud("woot");
  }

  /**
   * @covers TagadelicCloud::get_id
   */
  public function testGet_id() {
    $this->assertEquals(1337, $this->object->get_id());
  }

  /**
   * @covers TagadelicCloud::get_tags
   * @todo   Implement testGet_tags().
   */
  public function testGet_tags()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicCloud::add_tag
   * @todo   Implement testAdd_tag().
   */
  public function testAdd_tag()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicCloud::create_and_add_tag
   * @todo   Implement testCreate_and_add_tag().
   */
  public function testCreate_and_add_tag()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicCloud::cache_get
   * @todo   Implement testCache_get().
   */
  public function testCache_get()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }

  /**
   * @covers TagadelicCloud::cache_set
   * @todo   Implement testCache_set().
   */
  public function testCache_set()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
      'This test has not been implemented yet.'
    );
  }
}
